name: imagen
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  # utility
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.0+3
  cached_network_image: ^3.2.2

  # translate
  translator: ^0.1.7

  # network manager
  dio: ^4.0.6

  # state management
  provider: ^6.0.4

  # cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_image_viewer: ^1.2.0

  # Firebase
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  image_picker: ^0.8.6
  cloud_firestore: ^4.3.1
  uuid: ^3.0.7
  firebase_storage: ^11.0.10
  flutter_staggered_grid_view: ^0.6.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.14

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"

flutter_native_splash:
  image: "images/icon.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/images/
    - assets/showcase/