// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8Dmlks_XxBWKt_U4qQ72yoPAhrqQwj0',
    appId: '1:528547909665:android:58e5c09b0418915d199360',
    messagingSenderId: '528547909665',
    projectId: 'cisco-ai-ef87d',
    storageBucket: 'cisco-ai-ef87d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVUKYX6tgl5mtAEtdBAGCey8-wyJjLRg8',
    appId: '1:528547909665:ios:ce7b3d3ab663d3c5199360',
    messagingSenderId: '528547909665',
    projectId: 'cisco-ai-ef87d',
    storageBucket: 'cisco-ai-ef87d.appspot.com',
    androidClientId: '528547909665-08tu5448nh6g9vm6o7h8eh2lt08mfuh4.apps.googleusercontent.com',
    iosClientId: '528547909665-kbnkfkvrcnuumkapghrnunt8519tk1fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.imagan',
  );
}
